ENV_FILE_PATH = "../.env.analytics-instruct-multilingual-app.local"
PRODUCTION_MODE = "prod"
LOCAL_MODE = "local"

TASK_1_NAME = "Rate Model Performance"
TASK_2_NAME = "Contribute Your Language"

NUM_SUBMISSIONS_COL_NAME = "NUMBER OF UNIQUE SUBMISSIONS"
ALL_LANG_COL_NAME = "LANGUAGE"
ALL_REGION_COL_NAME = "REGION"

ALL_REGIONS_PLOT = "Overall Regional Leaderboard"

TOP_LANG_PLOT = "Overall Top 10 Languages"
TOP_CONTRIBUTOR_PLOT = "Overall Top 10 Contributors"
TOP_LANG_CONTRIBUTOR_PLOT = "Overall Top 10 Languages with most Contributors"

AFRICA_REGION = "AFRICA"
ASIA_REGION = "ASIA"
EUROPE_REGION = "EUROPE"
LATAM_REGION = "LATIN AMERICA"
OTHERS_REGION = "OTHERS"

LANG_NAME_ARABIC = "Arabic"
LANG_NAME_CHINESE = "Chinese"

LANGUAGE_REGION_DICT = {
    "AFRICA": [
        "Standard Arabic (Africa)",
        "Egyptian Arabic",
        "Tunisian Arabic",
        "Moroccan Arabic",
        "Plateau Malagasy",
        "Shona",
        "Yoruba",
        "Zulu",
        "Afrikaans",
        "Amharic",
        "Nyanja",
        "Hausa",
        "Igbo",
        "Somali",
        "Southern Sotho",
        "Northern Sotho",
        "Swahili (individual language)",
        "Xhosa",
        "Wolof",
    ],
    "ASIA": [
        "Mesopotamian Arabic",
        "Ta'izzi-Adeni Arabic",
        "South Levantine Arabic",
        "North Levantine Arabic",
        "Standard Arabic (Asia)",
        "Najdi Arabic",
        "Hebrew",
        "Burmese",
        "Simplified Chinese",
        "Traditional Chinese",
        "Hmong",
        "Indonesian",
        "Kazakh",
        "Northern Kurdish",
        "Central Kurdish",
        "Kyrgyz",
        "Lao",
        "Standard Malay",
        "Nepali (individual language)",
        "Panjabi",
        "Sundanese",
        "Thai",
        "Urdu",
        "Northern Uzbek",
        "Vietnamese",
        "Armenian",
        "South Azerbaijani",
        "North Azerbaijani",
        "Bengali",
        "Filipino",
        "Hindi",
        "Japanese",
        "Javanese",
        "Tamil",
        "Cebuano",
        "Gujarati",
        "Kannada",
        "Central Khmer",
        "Korean",
        "Malayalam",
        "Marathi",
        "Halh Mongolian",
        "Southern Pashto",
        "Iranian Persian",
        "Sindhi",
        "Sinhala",
        "Tajik",
        "Telugu",
        "Turkish",
    ],
    "EUROPE": [
        "Eastern Yiddish",
        "Tosk Albanian",
        "Basque",
        "Belarusian",
        "Bulgarian",
        "Catalan",
        "Corsican",
        "Czech",
        "Danish",
        "Dutch",
        "Esperanto",
        "Estonian",
        "Finnish",
        "French",
        "Galician",
        "Georgian",
        "German",
        "Modern Greek (1453-)",
        "Latin",
        "Luxembourgish",
        "Hungarian",
        "Icelandic",
        "Irish",
        "Italian",
        "Standard Latvian",
        "Lithuanian",
        "Macedonian",
        "Maltese",
        "Norwegian Nynorsk",
        "Norwegian Bokmål",
        "Polish",
        "Romanian",
        "Scottish Gaelic",
        "Serbian",
        "Slovak",
        "Slovenian",
        "Swedish",
        "Ukrainian",
        "Welsh",
        "Western Frisian",
        "Russian",
        "Portuguese (Europe)",
        "Spanish (Europe)",
    ],
    "LATIN AMERICA": [
        "Portuguese (LatAm)",
        "Spanish (LatAm)",
        "Haitian",
        "Hawaiian",
    ],
    "OTHERS": ["English","Maori","Samoan"],
}


DB_LANGUAGE_LIST = [
        "Standard Arabic",
        "Egyptian Arabic",
        "Tunisian Arabic",
        "Moroccan Arabic",
        "Plateau Malagasy",
        "Shona",
        "Yoruba",
        "Zulu",
        "Afrikaans",
        "Amharic",
        "Nyanja",
        "Hausa",
        "Igbo",
        "Somali",
        "Southern Sotho",
        "Northern Sotho",
        "Swahili (individual language)",
        "Xhosa",
        "Wolof",
        "Mesopotamian Arabic",
        "Ta'izzi-Adeni Arabic",
        "South Levantine Arabic",
        "North Levantine Arabic",
        "Najdi Arabic",
        "Hebrew",
        "Burmese",
        "Simplified Chinese",
        "Traditional Chinese",
        "Hmong",
        "Indonesian",
        "Kazakh",
        "Northern Kurdish",
        "Central Kurdish",
        "Kyrgyz",
        "Lao",
        "Standard Malay",
        "Nepali (individual language)",
        "Panjabi",
        "Sundanese",
        "Thai",
        "Urdu",
        "Northern Uzbek",
        "Vietnamese",
        "Armenian",
        "South Azerbaijani",
        "North Azerbaijani",
        "Bengali",
        "Filipino",
        "Hindi",
        "Japanese",
        "Javanese",
        "Tamil",
        "Cebuano",
        "Gujarati",
        "Kannada",
        "Central Khmer",
        "Korean",
        "Malayalam",
        "Marathi",
        "Halh Mongolian",
        "Southern Pashto",
        "Iranian Persian",
        "Sindhi",
        "Sinhala",
        "Tajik",
        "Telugu",
        "Turkish",
        "Eastern Yiddish",
        "Tosk Albanian",
        "Basque",
        "Belarusian",
        "Bulgarian",
        "Catalan",
        "Corsican",
        "Czech",
        "Danish",
        "Dutch",
        "Esperanto",
        "Estonian",
        "Finnish",
        "French",
        "Galician",
        "Georgian",
        "German",
        "Modern Greek (1453-)",
        "Latin",
        "Luxembourgish",
        "Hungarian",
        "Icelandic",
        "Irish",
        "Italian",
        "Standard Latvian",
        "Lithuanian",
        "Macedonian",
        "Maltese",
        "Norwegian Nynorsk",
        "Norwegian Bokmål",
        "Polish",
        "Romanian",
        "Scottish Gaelic",
        "Serbian",
        "Slovak",
        "Slovenian",
        "Swedish",
        "Ukrainian",
        "Welsh",
        "Western Frisian",
        "Russian",
        "Portuguese",
        "Spanish",
        "Haitian",
        "Hawaiian",
        "English",
        "Maori",
        "Samoan"
]


MT5_LANGUAGE_LIST = [
    "All Languages",
    "Arabic",
    "Malagasy",
    "Shona",
    "Yoruba",
    "Zulu",
    "Afrikaans",
    "Amharic",
    "Nyanja",
    "Hausa",
    "Igbo",
    "Somali",
    "Sotho",
    "Swahili",
    "Xhosa",
    "Wolof",
    "Hebrew",
    "Burmese",
    "Chinese",
    "Hmong",
    "Indonesian",
    "Kazakh",
    "Kurdish",
    "Kyrgyz",
    "Lao",
    "Malay",
    "Nepali",
    "Panjabi",
    "Sundanese",
    "Thai",
    "Urdu",
    "Uzbek",
    "Vietnamese",
    "Armenian",
    "Azerbaijani",
    "Bengali",
    "Filipino",
    "Hindi",
    "Japanese",
    "Javanese",
    "Tamil",
    "Cebuano",
    "Gujarati",
    "Kannada",
    "Khmer",
    "Korean",
    "Malayalam",
    "Marathi",
    "Mongolian",
    "Pashto",
    "Persian",
    "Sindhi",
    "Sinhala",
    "Tajik",
    "Telugu",
    "Turkish",
    "Yiddish",
    "Tosk Albanian",
    "Basque",
    "Belarusian",
    "Bulgarian",
    "Catalan",
    "Corsican",
    "Czech",
    "Danish",
    "Dutch",
    "Esperanto",
    "Estonian",
    "Finnish",
    "French",
    "Galician",
    "Georgian",
    "German",
    "Greek",
    "Latin",
    "Luxembourgish",
    "Hungarian",
    "Icelandic",
    "Irish",
    "Italian",
    "Standard Latvian",
    "Lithuanian",
    "Macedonian",
    "Maltese",
    "Norwegian Nynorsk",
    "Norwegian Bokmål",
    "Polish",
    "Romanian",
    "Scottish Gaelic",
    "Serbian",
    "Slovak",
    "Slovenian",
    "Swedish",
    "Ukrainian",
    "Welsh",
    "Western Frisian",
    "Russian",
    "Portuguese",
    "Spanish",
    "Haitian",
    "Hawaiian",
    "Maori",
    "Samoan"
]
